// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollSmootherWrapper from "./components/ScrollSmootherWrapper";
import Navbar from "./components/navbar/Navbar";
import { ErrorProvider } from "./context/ErrorProvider"; // <-- new

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gt webdevelopers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the app with ErrorProvider so error boundary can notify layout & navbar */}
        <ErrorProvider>
          {/* NAVBAR stays in the root layout but can now hide itself via context */}
          <Navbar />

          {/* ScrollSmootherWrapper wraps the rest of the page */}
          <ScrollSmootherWrapper>{children}</ScrollSmootherWrapper>
        </ErrorProvider>
      </body>
    </html>
  );
}
